[package]
name = "intervaltree"
version = "0.2.1"
authors = ["main() <main@ehvag.de>"]
license = "MIT"
description = "A simple and generic implementation of an immutable interval tree."

[dependencies]
smallvec = "0.4"
